//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSyraxSolutionsSAS.Vista.Admin
{
    public partial class DetalleProyecto
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Literal litTituloHeader;
        protected global::System.Web.UI.WebControls.Literal litInicial;
        protected global::System.Web.UI.WebControls.Literal litNombreUsuario;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlAlerta;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Literal litEstadoBadge;
        protected global::System.Web.UI.WebControls.Literal litEmpresa;
        protected global::System.Web.UI.WebControls.Literal litCliente;
        protected global::System.Web.UI.WebControls.Literal litTitulo;
        protected global::System.Web.UI.WebControls.Literal litDescripcion;
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;
        protected global::System.Web.UI.WebControls.Button btnActualizarEstado;
        protected global::System.Web.UI.WebControls.Literal litPorcentaje;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divProgresoBar;
        protected global::System.Web.UI.WebControls.Literal litFechaInicio;
        protected global::System.Web.UI.WebControls.Literal litFechaEntrega;
        protected global::System.Web.UI.WebControls.Literal litPrecio;
        protected global::System.Web.UI.WebControls.Literal litCardEmpresa;
        protected global::System.Web.UI.WebControls.Literal litCardCliente;
        protected global::System.Web.UI.WebControls.Literal litCardCorreo;
        protected global::System.Web.UI.WebControls.Literal litCardSuscripcion;
        protected global::System.Web.UI.WebControls.TextBox txtEvidencia;
        protected global::System.Web.UI.WebControls.Button btnGuardarAvance;
        protected global::System.Web.UI.WebControls.Repeater rptAvances;
        protected global::System.Web.UI.WebControls.Panel pnlSinAvances;
    }
}
