//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSyraxSolutionsSAS.Vista.Index
{
    public partial class Registro
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoDocumento;
        protected global::System.Web.UI.WebControls.TextBox txtNumeroDocumento;
        protected global::System.Web.UI.WebControls.TextBox txtNombres;
        protected global::System.Web.UI.WebControls.TextBox txtApellidos;
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;
        protected global::System.Web.UI.WebControls.TextBox txtClave;
        protected global::System.Web.UI.WebControls.TextBox txtNombreEmpresa;
        protected global::System.Web.UI.WebControls.TextBox txtNitEmpresa;
        protected global::System.Web.UI.WebControls.TextBox txtDireccionEmpresa;
        protected global::System.Web.UI.WebControls.TextBox txtTelefonoEmpresa;
        protected global::System.Web.UI.WebControls.TextBox txtDescripcionEmpresa;
        protected global::System.Web.UI.WebControls.Button btnRegistrar;
    }
}
